import {
  changePassword,
  login,
  register,
  sendChangePasswordOtp,
  sendRegisterOtp,
} from "./auth.controller.js";
import {
  createAdminAiLevel,
  createAdminExercise,
  createAdminVocabulary,
  deleteAdminAiLevel,
  deleteAdminExercise,
  deleteAdminVocabulary,
  getAdminAiLevels,
  getAdminExercises,
  getAdminOverview,
  getAdminReports,
  getAdminUsers,
  getAdminVocabulary,
  updateAdminAiLevel,
  updateAdminExercise,
  updateAdminVocabulary,
} from "./admin.controller.js";
import {
  getExerciseById,
  getExerciseHints,
  getExerciseHistory,
  getExerciseLeaderboard,
  getExerciseReview,
  getExerciseSummary,
  getRecommendedExercises,
  listExercises,
  submitExerciseAttempt,
} from "./exercise.controller.js";

const healthCheck = (_req, res) => {
  res.status(200).json({
    success: true,
    message: "API is healthy",
    timestamp: new Date().toISOString(),
  });
};

export {
  changePassword,
  createAdminAiLevel,
  createAdminExercise,
  createAdminVocabulary,
  deleteAdminAiLevel,
  deleteAdminExercise,
  deleteAdminVocabulary,
  getAdminAiLevels,
  getAdminExercises,
  getAdminOverview,
  getAdminReports,
  getAdminUsers,
  getAdminVocabulary,
  getExerciseById,
  getExerciseHints,
  getExerciseHistory,
  getExerciseLeaderboard,
  getExerciseReview,
  getExerciseSummary,
  getRecommendedExercises,
  healthCheck,
  listExercises,
  login,
  register,
  sendChangePasswordOtp,
  sendRegisterOtp,
  submitExerciseAttempt,
  updateAdminAiLevel,
  updateAdminExercise,
  updateAdminVocabulary,
};
