import {
  changePassword,
  login,
  register,
  sendChangePasswordOtp,
  sendRegisterOtp,
} from "./auth.controller.js";
import {
  createAdminAiLevel,
  deleteAdminAiLevel,
  getAdminAiLevels,
  updateAdminAiLevel,
  uploadAdminImage,
} from "./ai.controller.js";
import {
  activateAdminPlacementTest,
  confirmPlacementResult,
  createAdminPlacementTest,
  deleteAdminPlacementTest,
  getActivePlacementTest,
  getAdminPlacementTestById,
  getAdminPlacementTests,
  getPlacementAttemptById,
  skipPlacementTest,
  submitPlacementTest,
  updateAdminPlacementTest,
} from "./placement.controller.js";
import {
  createAdminExercise,
  deleteAdminExercise,
  getAdminExercises,
  getExerciseById,
  getExerciseHints,
  getExerciseHistory,
  getExerciseLeaderboard,
  getExerciseReview,
  getExerciseSummary,
  getRecommendedExercises,
  listExercises,
  submitExerciseAttempt,
  updateAdminExercise,
} from "./exercise.controller.js";
import {
  getAdminOverview,
  getAdminReports,
  getAdminUsers,
} from "./user.controller.js";
import {
  createAdminVocabulary,
  createAdminVocabularyWord,
  createAdminVocabularyWordsBulk,
  deleteAdminVocabulary,
  deleteAdminVocabularyWord,
  getAdminVocabulary,
  getAdminVocabularyById,
  getAdminVocabularyWords,
  getRecommendedVocabularies,
  getVocabularyById,
  getVocabularyHints,
  getVocabularyHistory,
  getVocabularyLeaderboard,
  getVocabularyReview,
  getVocabularySummary,
  listVocabularies,
  submitVocabularyAttempt,
  updateAdminVocabulary,
  updateAdminVocabularyWord,
} from "./vocabulary.controller.js";

const healthCheck = (_req, res) => {
  res.status(200).json({
    success: true,
    message: "API is healthy",
    timestamp: new Date().toISOString(),
  });
};

export {
  activateAdminPlacementTest,
  changePassword,
  confirmPlacementResult,
  createAdminAiLevel,
  createAdminExercise,
  createAdminPlacementTest,
  createAdminVocabulary,
  createAdminVocabularyWord,
  createAdminVocabularyWordsBulk,
  deleteAdminAiLevel,
  deleteAdminExercise,
  deleteAdminPlacementTest,
  deleteAdminVocabulary,
  deleteAdminVocabularyWord,
  getActivePlacementTest,
  getAdminAiLevels,
  getAdminExercises,
  getAdminOverview,
  getAdminPlacementTestById,
  getAdminPlacementTests,
  getAdminReports,
  getAdminUsers,
  getAdminVocabulary,
  getAdminVocabularyById,
  getAdminVocabularyWords,
  getExerciseById,
  getExerciseHints,
  getExerciseHistory,
  getExerciseLeaderboard,
  getExerciseReview,
  getExerciseSummary,
  getPlacementAttemptById,
  getRecommendedExercises,
  getRecommendedVocabularies,
  getVocabularyById,
  getVocabularyHints,
  getVocabularyHistory,
  getVocabularyLeaderboard,
  getVocabularyReview,
  getVocabularySummary,
  healthCheck,
  listExercises,
  listVocabularies,
  login,
  register,
  sendChangePasswordOtp,
  sendRegisterOtp,
  skipPlacementTest,
  submitExerciseAttempt,
  submitPlacementTest,
  submitVocabularyAttempt,
  updateAdminAiLevel,
  updateAdminExercise,
  updateAdminPlacementTest,
  updateAdminVocabulary,
  updateAdminVocabularyWord,
  uploadAdminImage,
};
