import {
  changePassword,
  login,
  register,
  sendChangePasswordOtp,
  sendRegisterOtp,
} from "./auth.controller.js";
import {
  activateAdminPlacementTest,
  confirmPlacementResult,
  createAdminPlacementTest,
  createAdminPlacementTestWithAi,
  deleteAdminPlacementTest,
  getActivePlacementTest,
  getAdminPlacementTestById,
  getAdminPlacementTests,
  getPlacementAttemptById,
  skipPlacementTest,
  submitPlacementTest,
  updateAdminPlacementTest,
} from "./placement.controller.js";
import {
  createAdminExercise,
  deleteAdminExercise,
  getAdminExercises,
  getExerciseById,
  getExerciseHints,
  getExerciseHistory,
  getExerciseLeaderboard,
  getExerciseReview,
  getExerciseSummary,
  getRecommendedExercises,
  listExercises,
  submitExerciseAttempt,
  updateAdminExercise,
} from "./exercise.controller.js";
import {
  createUserAiExercise,
  deleteUserAiExercise,
  generateExerciseAiFromPdf,
  generateExerciseAiFromPrompt,
  updateUserAiExercise,
} from "./exercise-ai.controller.js";
import {
  createAdminUser,
  deleteAdminUser,
  getAdminOverview,
  getAdminReports,
  getAdminUserById,
  getAdminUsers,
  resetAdminUserPassword,
  updateAdminUser,
  updateAdminUserRole,
  updateAdminUserStatus,
} from "./user.controller.js";
import {
  createAdminVocabulary,
  createAdminVocabularyWord,
  createAdminVocabularyWordsBulk,
  deleteAdminVocabulary,
  deleteAdminVocabularyWord,
  getAdminVocabulary,
  getAdminVocabularyById,
  getAdminVocabularyWords,
  getRecommendedVocabularies,
  getVocabularyById,
  getVocabularyHints,
  getVocabularyHistory,
  getVocabularyLeaderboard,
  getVocabularyReview,
  getVocabularySummary,
  listVocabularies,
  submitVocabularyAttempt,
  updateAdminVocabulary,
  updateAdminVocabularyWord,
} from "./vocabulary.controller.js";

const healthCheck = (_req, res) => {
  res.status(200).json({
    success: true,
    message: "API is healthy",
    timestamp: new Date().toISOString(),
  });
};

export {
  activateAdminPlacementTest,
  changePassword,
  confirmPlacementResult,
  createAdminExercise,
  createUserAiExercise,
  createAdminPlacementTest,
  createAdminPlacementTestWithAi,
  createAdminUser,
  createAdminVocabulary,
  createAdminVocabularyWord,
  createAdminVocabularyWordsBulk,
  deleteAdminExercise,
  deleteUserAiExercise,
  deleteAdminPlacementTest,
  deleteAdminUser,
  deleteAdminVocabulary,
  deleteAdminVocabularyWord,
  generateExerciseAiFromPdf,
  generateExerciseAiFromPrompt,
  getActivePlacementTest,
  getAdminExercises,
  getAdminOverview,
  getAdminPlacementTestById,
  getAdminPlacementTests,
  getAdminReports,
  getAdminUserById,
  getAdminUsers,
  getAdminVocabulary,
  getAdminVocabularyById,
  getAdminVocabularyWords,
  getExerciseById,
  getExerciseHints,
  getExerciseHistory,
  getExerciseLeaderboard,
  getExerciseReview,
  getExerciseSummary,
  getPlacementAttemptById,
  getRecommendedExercises,
  getRecommendedVocabularies,
  getVocabularyById,
  getVocabularyHints,
  getVocabularyHistory,
  getVocabularyLeaderboard,
  getVocabularyReview,
  getVocabularySummary,
  healthCheck,
  listExercises,
  listVocabularies,
  login,
  register,
  resetAdminUserPassword,
  sendChangePasswordOtp,
  sendRegisterOtp,
  skipPlacementTest,
  submitExerciseAttempt,
  submitPlacementTest,
  submitVocabularyAttempt,
  updateAdminExercise,
  updateUserAiExercise,
  updateAdminPlacementTest,
  updateAdminUser,
  updateAdminUserRole,
  updateAdminUserStatus,
  updateAdminVocabulary,
  updateAdminVocabularyWord,
};
